config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :transactions
  resources :allowances
end

app/models/budget.rb
class Budget
  include Mongoid::Document
  include Mongoid::Timestamps

  include Currentable

  field :name, type: String
  field :start_date, type: DateTime
  field :end_date, type: DateTime

  def transactions
    Transaction.where(created_at: {"$gte": start_date, "$lte": end_date})
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  attr_reader :budgets, :budget
  helper_method :budgets, :budget

  before_action :set_budget, only: %i[ show edit update destroy ]

  def index
    @budgets = Budget.all
  end

  def show
  end

  def new
    @budget = Budget.new
  end

  def create
    @budget = Budget.new(budget_params)

    if budget.save
      respond_to do |format|
        format.html { redirect_to budget, notice: "Budget was successfully created." }
        format.json { render :show, status: :created, location: budget }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if budget.update(budget_params)
        format.html { redirect_to budget, notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: budget.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_budget
    @budget = Budget.find(params[:id])
  end

  def budget_params
    params.require(:budget).permit(:name, :start_date, :end_date)
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: budget, local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>

  <%= form.label :start_date, "Start Date:" %>
  <%= form.datetime_local_field :start_date %>

  <%= form.label :end_date, "End Date:" %>
  <%= form.datetime_local_field :end_date %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/_transactions.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= budget.name %> Transactions</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% transactions.each do |transaction| %>
    <br>
    <td>Amount: <%= transaction.amount %></td>
    <td>Type: <%= transaction.type %></td>
    <td>Description: <%= transaction.description %></td>
    <td>Allowances: <%= allowance_names(transaction.splits.pluck(:allowance)).join(",") %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/budgets/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', budget: budget %>

<%= link_to 'Show', budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% budgets.each do |budget| %>
    <br>
    <tr>
      <td>Name: <%= budget.name %></td>
      <td>Start: <%= budget.start_date %></td>
      <td>End: <%= budget.end_date %></td>
      <td><%= link_to 'Show', budget %></td>
      <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
      <td><%= link_to 'Destroy', budget_path(budget), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: budget %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Name: <%= budget.name %><br/>
  Start Date: <%= budget.start_date %> <br/>
  End Date: <%= budget.end_date %> <br/>
  <%= render "transactions", budget: budget, transactions: budget.transactions %>

</p>

<%= link_to 'Edit', edit_budget_path(budget) %> |
<%= link_to 'Back', budgets_path %>