config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :transactions
  resources :allowances
end

app/models/allowance.rb
class Allowance
  UNCATEGORIZED = "Uncategorized".freeze

  include Mongoid::Document

  field :name, type: String
  field :starting_amount, type: Money, default: Money.new(0)
  field :planned, type: Money, default: Money.new(0)
  field :spent, type: Money, default: Money.new(0)
  field :category, type: String, default: UNCATEGORIZED
  field :start_date, type: DateTime, default: DateTime.now
  field :end_date, type: DateTime

  validates :name, uniqueness: { case_sensitive: false }

  # scope :for_current_budget, -> { where(start_date: {"$gte": current_budget.begin}, end_date: {"$lt": current_budget.end}) }

  def left_to_spend
    planned - spent
  end

  # @todo store value for `current_budget` that is a dropdown at the top of screen that always has a value and defaults
  # to beginning of month to end of month.
  def transactions
    # @todo a scope that eases querying for transactions in a particular budget
    Transaction.where(
      "$and": [
        transaction_date: { "$gte": start_date },
        transaction_date: { "$lte": end_date },
      ]
    )
  end
end

app/controllers/allowances_controller.rb
class AllowancesController < ApplicationController
  attr_reader :allowance, :allowances
  helper_method :allowance, :allowances

  before_action :set_allowance, only: %i[ show edit update destroy ]

  # GET /allowances or /allowances.json
  def index
    @allowances = Allowance.all
  end

  # GET /allowances/1 or /allowances/1.json
  def show
  end

  # GET /allowances/new
  def new
    @allowance = Allowance.new
  end

  def create
    @allowance = Allowance.new(allowance_params)

    if allowance.save
      respond_to do |format|
        format.html { redirect_to allowance, notice: "Allowance was successfully created." }
        format.json { render :show, status: :created, location: allowance }
      end
    end
  end

  # GET /allowances/1/edit
  def edit
  end

  # PATCH/PUT /allowances/1 or /allowances/1.json
  def update
    respond_to do |format|
      if allowance.update(allowance_params)
        format.html { redirect_to allowance, notice: "Allowance was successfully updated." }
        format.json { render :show, status: :ok, location: allowance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: allowance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allowances/1 or /allowances/1.json
  def destroy
    allowance.destroy
    respond_to do |format|
      format.html { redirect_to allowances_url, notice: "Allowance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_allowance
    @allowance = Allowance.find(params[:id])
  end

  def allowance_params
    params.require(:allowance).permit(:name, :starting_amount, :planned, :category).merge(budget_params)
  end

  def budget_params
    budget_params = params.require(:allowance).permit(:budget)
    budget = Budget.find(budget_params[:budget])

    { start_date: budget.start_date, end_date: budget.end_date }
  end
end

app/helpers/allowances_helper.rb
module AllowancesHelper
  def budget_options
    Budget.all.map { |budget|  [budget.name.capitalize, budget.id] }
  end
end

app/views/allowances/_form.html.erb
<%= form_with(model: allowance, local: true) do |form| %>
  <% if allowance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(allowance.errors.count, "error") %> prohibited this allowance from being saved:</h2>

      <ul>
        <% allowance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>

  <%= form.label :starting_amount, "Starting Amount:" %>
  <%= form.number_field :starting_amount, in: 0.0..1000000.0 %>

  <%= form.label :planned, "Planned:" %>
  <%= form.number_field :planned, in: 0.0..1000000.0 %>

  <%= form.label :spent, "Spent:" %>
  <%= form.number_field :spent, in: 0.0..1000000.0 %>

  <%= form.label :name, "Category:" %>
  <%= form.text_field :category %>

  <%= form.label :budget, "Budget:" %>
  <%= form.select :budget, budget_options %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/allowances/_transactions.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= allowance.name %> Transactions</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% transactions.each do |transaction| %>
    <br>
    <td>Amount: <%= transaction.amount %></td>
    <td>Type: <%= transaction.type %></td>
    <td>Description: <%= transaction.description %></td>
    <td>Allowances: <%= allowance_names(transaction.splits.pluck(:allowance)).join(",") %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/allowances/edit.html.erb
<h1>Editing Allowance</h1>

<%= render 'form', allowance: allowance %>

<%= link_to 'Show', allowance %> |
<%= link_to 'Back', allowances_path %>

app/views/allowances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Allowances</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% allowances.each do |allowance| %>
    <br>
    <tr>
      <td>Name: <%= allowance.name %></td>
      <td>Starting Amount: <%= allowance.starting_amount %></td>
      <td>Planned: <%= allowance.planned %></td>
      <td>Spent: <%= allowance.spent %></td>
      <td>Category: <%= allowance.category %></td>
      <td>Start Date: <%= allowance.start_date %></td>
      <td>End Date: <%= allowance.end_date %></td>
      <td><%= link_to 'Show', allowance %></td>
      <td><%= link_to 'Edit', edit_allowance_path(allowance) %></td>
      <td><%= link_to 'Destroy', allowance_path(allowance), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allowance', new_allowance_path %>

app/views/allowances/new.html.erb
<h1>New Allowance</h1>

<%= render 'form', allowance: allowance %>

<%= link_to 'Back', allowances_path %>

app/views/allowances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Name: <%= allowance.name %><br/>
  Starting Amount: <%= allowance.starting_amount %> <br/>
  Planned: <%= allowance.planned %> <br/>
  Spent: <%= allowance.spent %> <br/>
  Category: <%= allowance.category %> <br/>
  Start Date: <%= allowance.start_date %> <br/>
  End Date: <%= allowance.end_date %> <br/>
  <%= render "transactions", allowance: allowance, transactions: allowance.transactions %>
</p>

<%= link_to 'Edit', edit_allowance_path(allowance) %> |
<%= link_to 'Back', allowances_path %>